# Generated by Django 3.1 on 2020-08-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STIL_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime_field', models.DateTimeField(verbose_name='start_date')),
                ('end_datetime_field', models.DateTimeField(verbose_name='end_date')),
                ('fom', models.IntegerField()),
                ('id_record', models.CharField(max_length=100)),
                ('discusson', models.CharField(max_length=400)),
            ],
        ),
    ]
